### ISSUE TITLE
Missing value at path for something that is nested in an if statement

### ISSUE THREAD

**Issue by iammoen** [tim-koehler/Helm-Intellisense#14]
We are using a chart that has a lot of values that will only be put into the output of helm if the value path exists. Example:

```yaml
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
```

But when I lint this it tells me that "Missing value at path [.Values.image.pullSecret]" for the 3rd line. Even putting a default value in for it doesn't stop the lint error. Thoughts on making the linter ok with the value path being called in an if statement?
